{
 "title": "DevOpstic Dashboard",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "query": "select distinct(pipeline_id) from events"
   },
   {
    "name": "env",
    "query": "select distinct(environment) from events"
   }
  ]
 },
 "panels": [
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Deployments",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT commit_id, timestamp, status\nfrom events\nwhere pipeline_id='$pipeline'\nand environment='$env'\nand type='deploy'\norder by timestamp desc\nlimit 2"
    }
   ]
  },
  { "title": "Throughput & Stability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Deployments per day",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  ROUND(60*60*24*count(*)/($__unixEpochTo()-$__unixEpochFrom())::numeric,2)\nFROM\n  events\nWHERE\n  $__timeFilter(timestamp) \n  AND type = 'deploy'\n  AND environment = '$env'\n  AND pipeline_id='$pipeline'\n"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT failure_count/(success_count+failure_count)\nFROM ( SELECT\n  ROUND(60*60*24*count(*)/($__unixEpochTo()-$__unixEpochFrom())::numeric,2) as success_count\nFROM\n  events\nWHERE\n  $__timeFilter(timestamp) \n  AND type = 'deploy'\n  AND status = 'success'\n  AND environment = '$env'\n  AND pipeline_id='$pipeline'\n) AS success,\n(SELECT\n  ROUND(60*60*24*count(*)/($__unixEpochTo()-$__unixEpochFrom())::numeric,2) as failure_count\nFROM\n  events\nWHERE\n  $__timeFilter(timestamp) \n  AND type = 'deploy'\n  AND status = 'failure'\n  AND environment = '$env'\n  AND pipeline_id='$pipeline'\n) as failure"
    }
   ]
  },
  {
   "title": "Time to Restore Service",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  avg(time_to_restore/60)\nFROM\n  incidents\nWHERE\n  $__timeFilter(resolution_time) \n  AND state = 'resolved'\n  AND environment = '$env'\n  AND time_to_restore IS NOT NULL\n  AND pipeline_id='$pipeline'\n"
    }
   ]
  },
  { "title": "Lead Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Lead Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  AVG((c.review_lead_time+d.lead_time)/60)\nFROM\n  commits as c\nright join deployments as d\non c.commit_id = d.commit_id\nAND c.pipeline_id = d.pipeline_id\nWHERE\n  $__timeFilter(d.timestamp) \nAND d.environment = '$env'\nAND c.pipeline_id='$pipeline'\n"
    }
   ]
  },
  {
   "title": "Review Lead Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  AVG(commits.review_lead_time/60)\nFROM\n  commits\nWHERE\n  $__timeFilter(commits.approval_time) \nAND (commits.state = 'approved' OR commits.state = 'deployed')\nAND pipeline_id='$pipeline'\nand review_lead_time is not null\nand review_lead_time > 0\n\n"
    }
   ]
  },
  {
   "title": "Deployment Lead Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  AVG(lead_time/60)\nFROM\n  deployments\n  join commits on commits.commit_id = deployments.commit_id\nWHERE\n  $__timeFilter(deployments.timestamp) \nAND deployments.environment = '$env'\nAND commits.pipeline_id='$pipeline'\nand lead_time is not null\nand lead_time > 0\n"
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recent events",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT environment, timestamp, type, commit_id, pull_request_id, status\nfrom events\nwhere pipeline_id='$pipeline'\nand $__timeFilter(timestamp)"
      }
     ]
    },
    {
     "title": "Commits",
     "type": "table",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT  c.commit_id, commit_time, submit_time, approval_time, d.timestamp as deployment_time, pull_request_id, state, ((review_lead_time+d.lead_time)/60) as total_lead_time, (review_lead_time/60) as review_lead_time, (d.lead_time/60) as deployment_lead_time\nfrom commits as c\nleft join deployments as d on d.commit_id = c.commit_id\nwhere $__timeFilter(c.approval_time) \nAND c.pipeline_id='$pipeline'\norder by c.commit_time desc"
      }
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Deployments",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  deployments\n  \nWHERE\n  $__timeFilter(deployments.timestamp) \nAND deployments.environment = '$env'\n"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  review_lead_time/60, commit_id\nFROM\n  commits\nWHERE\n  $__timeFilter(commits.approval_time) \nAND (commits.state = 'approved' OR commits.state = 'deployed')\nAND pipeline_id=$pipeline\nand review_lead_time > 0"
    }
   ]
  }
 ]
}